### ISSUE TITLE
Version in source control does not match npm

### ISSUE THREAD

**Issue by jprianos-accusoft** [jquery/eslint-config-jquery#13]
Running an npm install of this module results in 1.0.1 being installed. The source in github shows 1.0.0. This came up in an audit of licenses for dependencies where the specific version of each dependency was being reviewed and we can't find source for the 1.0.1 release.

**Comment by mgol** [comment]
Thanks for the report.

@markelog Do you know something about that?

**Comment by markelog** [comment]
Heh, not sure, my fork is updated but this version is not, apparently one commit was lost during the move.

Pushed the changes, not it should be correct. 

@jprianos-accusoft thanks for noticing
