### ISSUE TITLE
Enable some eslint:recommended rules

### ISSUE THREAD

**Issue by edg2s** [jquery/eslint-config-jquery#15]
It would be nice to extend eslint:recommended, but to being with we should enable:
* `no-irregular-whitespace` - triggers once in jquery/jquery, a valid error on 103:72 of build/release.dist.js (tab instead of space)
* `no-extra-semi` - triggers in nodeName.js and isAutoPx.js. These extra semi colons can be removed.

**Comment by mgol** [comment]
I like the idea of adding `no-extra-semi` but I'm not sure of `no-irregular-whitespace`. As far as I understand, it detects spaces after tabs in an example like:
```js
	/**
	 * Clone the distribution repo
	 */
```
where the space is used to align a JSDoc-style comment properly.

Thoughts about those rules, @jquery/core?

**Comment by SharakPL** [comment]
I've used eslint default config for my jquery projects so far and with this jquery config every .js file is filled with errors. I feel like authors of this config try to make it different from `eslint:recommended` in every possible way and it's really not a good idea. I believe it should only differ in jquery specific rules.

**Comment by mgol** [comment]
@SharakPL You can't use a default ESLint config for all projects that may have their own configs. If your ESLint does that, it's configured incorrectly.

Also, the jQuery code style is way older than the ESLint recommended preset and it's even a few years (!) older than ESLint itself.

**Comment by SharakPL** [comment]
@mgol yeah, just like jquery. Another reason to make it up to date, at least with coding standards ;)

**Comment by mgol** [comment]
Code formatting rules are a question of personal taste and we don't want to changed them just for the sake of changing; that would generate big diffs & would make it harder to track when particular changes were introduced.

Let's focus on the proposed changes to the config here.

**Comment by SharakPL** [comment]
You're right. Good luck.

**Comment by mgol** [comment]
@edg2s We decided we want both rules enabled (my initial comment was incorrect as those JSDoc rules are exempt from the check already). Would you like to submit a PR?

**Comment by mgol** [comment]
PR: #16
