### ISSUE TITLE
Re-enable `no-unused-expressions` rule

### ISSUE THREAD

**Issue by markelog** [jquery/eslint-config-jquery#7]
It was disabled because of the cases like this -
https://github.com/jquery/jquery/blob/93f706200c6101df137469ba2e0d965e93508991/src/css/showHide.js#L21

But it seems like it is an issue with our code and with eslint too - https://github.com/eslint/eslint/issues/6636

**Comment by platinumazure** [comment]
I've left a comment on the ESLint issue. I don't think the logic should change (and I would consider the "violations" to be actual code style issues, in my opinion), but I think the error message could be improved.

In the meanwhile, would it help for someone to submit a PR to jQuery and other projects fixing those issues? (One could just turn the rule on locally and replace the commas with semicolons, basically, and then commit the fixes without enabling the rule.)

**Comment by markelog** [comment]
>  would it help for someone to submit a PR to jQuery and other projects fixing those issues? 

I already did that, no worries
