### ISSUE TITLE
Add `consistent-return` rule

### ISSUE THREAD

**Issue by markelog** [jquery/eslint-config-jquery#8]
With `treatUndefinedAsUnspecified` enabled, see http://eslint.org/docs/rules/consistent-return

Lots of errors with this one on Core

**Comment by mgol** [comment]
I don't think we can enable this rule, it would require Core API changes. If we disabled `treatUndefinedAsUnspecified` then perhaps it'd be possible.

**Comment by markelog** [comment]
I meant `treatUndefinedAsUnspecified: true`, this, it seems, will adhere to our style a bit better

**Comment by markelog** [comment]
Yeah, re-read the docs, probably not a good fit, please re-open, if you feel differently

**Comment by mgol** [comment]
Yeah, I agree. I'd expect this rule to have a mode that allows a function to only work in one of two modes:

1. `return something` is not allowed, bare `return` is allowed
2. `return something` is allowed but every function execution flow must end with an explicit `return something`

Such a rule could have an option to allow or disallow `return undefined` which we'd set to "allow".

I'm quite surprised this rule can't be configured to work in such a way. Do you think it could be extended in ESLint?

**Comment by markelog** [comment]
Yeah, i think it is worth a discussion at least
