### ISSUE TITLE
Add `eslint-plugin-import` as dependency

### ISSUE THREAD

**Issue by markelog** [jquery/eslint-config-jquery#9]
Because of the https://github.com/eslint/eslint/issues/3458, we can do this only as peer dep, but since I hopefully tackle that issue, we would eventually include this, since this thing support `amd` stuff, which is relevant to the core

/cc @timmywil

**Comment by platinumazure** [comment]
Maybe too specific if the goal is "AMD support" rather than specifically "RequireJS support", but have you looked at [eslint-plugin-requirejs](https://github.com/cvisco/eslint-plugin-requirejs)?

**Comment by markelog** [comment]
Looks good! Will check it out, thank you for the link
